Repository AY2223S2-CS2103T-T17-3/tp, pull requests merged in 2023-03, with the labels that each got.

#30 Implement delete_tag command.
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java
Labels: type.Story, type.Task, priority.High, severity.High

#32 Extend help
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High

#35 Add Filter Command
  .github/check-eof-newline.sh
  .github/check-line-endings.sh
  .github/check-trailing-whitespace.sh
  .github/run-checks.sh
  .gitignore
  gradlew
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/FieldsMatchRegexPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/CsvAdaptedPerson.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
Labels: type.Story, priority.Medium

#36 Fix GUI not update after delete_tag command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java
Labels: type.Bug, priority.High, severity.Low

#55 Friendlier syntax
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#61 Add Undo & Redo Commands
  docs/team/jefrai.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RedoCommandParser.java
  src/main/java/seedu/address/logic/parser/UndoCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/DeepCopyable.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/StateHistory.java
  src/main/java/seedu/address/model/person/Income.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RedoCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UndoCommandParserTest.java
  src/test/java/seedu/address/model/StateHistoryTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Story, priority.Medium

#67 Add history implementation in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.High

#66 Implement a history component displays previous executed commands.
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/TxtUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/history/History.java
  src/main/java/seedu/address/storage/HistoryStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TxtHistoryStorage.java
  src/main/java/seedu/address/ui/HistoryDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HistoryDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium

#78 Fix Mass command tests
  src/main/java/seedu/address/logic/commands/MassOpCommand.java
  src/main/java/seedu/address/logic/parser/MassOpCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/MassOpCommandTest.java
  src/test/java/seedu/address/logic/parser/MassOpCommandParserTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.Medium

#80 Add Freeze & Unfreeze Commands
  src/main/java/seedu/address/logic/commands/FreezeCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/UnfreezeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/exceptions/ModifyFrozenStateException.java
  src/main/java/seedu/address/model/person/ParticularPersonsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FreezeCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/UnfreezeCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java
Labels: type.Story, priority.Medium

#82 change MassOpCommand and MassOpCommandParser
  src/main/java/seedu/address/logic/commands/MassOpCommand.java
  src/main/java/seedu/address/logic/parser/MassOpCommandParser.java
  src/test/java/seedu/address/logic/commands/MassOpCommandTest.java
  src/test/java/seedu/address/logic/parser/MassOpCommandParserTest.java
Labels: priority.Medium

#83 Rectify Freeze & Unfreeze Commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/StateHistory.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/FreezeCommandTest.java
Labels: type.Bug, priority.High, severity.Low

#89 Improve Mass Operation Command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/MassOpCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/ShortcutCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/MassOpCommandParser.java
  src/main/java/seedu/address/logic/parser/ShortcutCommandParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/MassOpCommandTest.java
  src/test/java/seedu/address/logic/parser/MassOpCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#92 Final v1.3 additions
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/history/InputHistory.java
  src/main/resources/view/HistoryDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Task, priority.High

#93 Fix JavaFX exit procedure
  src/main/java/seedu/address/MainApp.java
Labels: type.Bug, severity.Medium

#95 Applying filter display
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/model/Filter.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/FieldsMatchRegexPredicate.java
  src/main/java/seedu/address/ui/FiltersDisplay.java
  src/main/java/seedu/address/ui/HistoryDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/FiltersDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, type.Enhancement, priority.Medium

#96 Update version, UserGuide.md
  build.gradle
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addExample.png
  docs/images/deleteExample.png
  docs/images/deleteTagExample.png
  docs/images/editExample.png
  docs/images/filtersDisplay.png
  docs/images/helpMessage.png
  docs/images/historyDisplay.png
  docs/images/listExample.png
  docs/images/tagExample.png
  src/main/java/seedu/address/MainApp.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.High
