Repository AY2223S2-CS2103T-T17-3/tp, pull requests merged in 2023-04, with the labels that each got.

#145 Fix Filter bug
  src/main/java/seedu/address/model/person/FieldsMatchRegexPredicate.java
Labels: type.Bug, priority.High, severity.High

#147 Edit PPP
  docs/DeveloperGuide.md
  docs/team/jefrai.md
Labels: type.Task

#148 Fix UG documentation bug of tag section from PE-D
  docs/UserGuide.md
Labels: type.Bug, priority.High

#149 PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/TagSequenceDiagram.puml
  docs/team/leonpoh.md
  src/main/java/seedu/address/model/person/Income.java
Labels: type.Task

#156 Fix PE-D bugs
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/hhchinh2002.md
  docs/team/jefrai.md
  docs/team/leonpoh.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ShortcutCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ShortcutCommandParser.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/model/Elister.java
  src/main/java/seedu/address/model/Filter.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/history/InputHistory.java
  src/main/java/seedu/address/model/person/Income.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Tag.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/CsvAdaptedPerson.java
  src/main/java/seedu/address/storage/CsvAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/TxtInputHistoryStorage.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/address/logic/commands/FreezeCommandTest.java
  src/test/java/seedu/address/logic/commands/MassOpCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/ShortcutCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/UnfreezeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ElisterParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ShortcutCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High
